server:
  port: 8700
  tomcat:
    connection-timeout: 18000000
websocket: 
  #test 环境
  #address: localhost:9090
  address: localhost:8700
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wdzj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    #数据库方言设置
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        jdbc:
          batch_size:  500
          batch_versioned_data: true
  thymeleaf:
    cache: false 
    #fileuploadSize
  servelt:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB
#wps convert
wps:
  domain: 
  appid:
  appsecret:
  convert:
    appid:
    appsecret:
    convert:
    query:
# upload
# qn oss   
upload:
  file-location:    
#OSS
oss:
  file_url_prefix:
  bucket_name:
  disk_name:
  region_id:
  endpoint:
  access_key:
  access_secret:
#QN
qn:
  access-key:
  secret-key:
  bucket:
  disk-name:
  url:
    
